services:

  configserver:
    image: coralieperez/configserver
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - climbingbuddy-networks
    mem_limit: 700m


  eurekaserver:
    image: coralieperez/eurekaserver
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    networks:
      - climbingbuddy-networks
    mem_limit: 700m
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s

    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/



  mysql:
    image: mysql
    container_name: mysql_climbingbuddy
    environment:
      MYSQL_DATABASE: climbingbuddy
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: courgette123
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      start_period: 10s
    ports:
      - 3308:3306
    networks:
      - climbingbuddy-networks



  mongo:
    image: mongo
    container_name: mongodb_climbingbuddy
    environment:
      MONGO_INITDB_DATABASE: techsheets
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: courgette123
    ports:
      - 27018:27017
#    healthcheck:
#      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
#      interval: 10s
#      timeout: 10s
#      retries: 5
#      start_period: 10s
    networks:
      - climbingbuddy-networks


  web-app:
    image: coralieperez/web-app
    container_name: web-app-climbingbuddy
    ports:
      - "8080:8080"
    networks:
      - climbingbuddy-networks
    mem_limit: 700m
    depends_on:
      - eurekaserver
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

  climb:
    image: coralieperez/climb
    container_name: climb-ms
    ports:
      - "9000:9000"
    networks:
      - climbingbuddy-networks
    depends_on:
      - mysql
      - eurekaserver
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/climbingbuddy"

  sheets:
    image: coralieperez/sheets
    container_name: sheets-ms
    ports:
      - "9020:9020"
    depends_on:
      eurekaserver:
        condition: service_healthy
    networks:
      - climbingbuddy-networks
    mem_limit: 700m
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_HOST: mongo



networks:
  climbingbuddy-networks: