spring:
  application:
    name: configserver

  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native
          # search-locations: "classpath:/config"
          # search-locations: "file:///users//coralieperez//Documents//config"
        git:
          uri: https://github.com/CoralieP98/climbingBuddy-config
          default-label: main
          timeout: 5000
          clone-on-start: true
          force-pull: true

###

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

server:
  port: 8071


