spring:
  application:
    name: configserver

  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/CoralieP98/climbingBuddy-config"
          default-label: main
          timeout: 5000
          clone-on-start: true
          force-pull: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

server:
  port: 8071


